Update python binding build docs
arvidn/libtorrent pull request #5917
Opened 2021-01-27 02:18 UTC by AllSeeingEyeTolledEweSew

This should reflect how things currently work

2021-02-07 23:22 UTC, arvidn requested changes
looks good. sorry for the delay. It should probably be updated to mention `--b2-args=` instead now though. I will back-port some of this to `RC_1_2`

2021-02-07 23:22 UTC, arvidn commented on docs/python_binding.rst
> +	python setup.py build_ext --optimization=space install
a few of these are outdated with the new `--b2-args=` argument

2021-02-08 00:19 UTC, AllSeeingEyeTolledEweSew commented
Should I just move these changes into #5948 and modify as appropriate?

2021-02-10 22:02 UTC, AllSeeingEyeTolledEweSew commented
Done externally

2021-02-10 22:02 UTC, closed without merging