i2p_socket flag
arvidn/libtorrent pull request #7301
Opened 2023-02-11 08:17 UTC by jiigen

Make i2p_socket flag available to python.
Use case: Python clients can use it to distinguish i2p peers from regular ones.

2023-02-11 12:31 UTC, arvidn requested changes

2023-02-11 14:06 UTC, jiigen commented on bindings/python/src/peer_info.cpp
> +    pi.attr("i2p_socket") = peer.info::i2p_socket;
> peer_info::i2p_socket

Yes

2023-02-12 06:46 UTC, jiigen commented
@arvidn I fixed the typo.

2023-02-12 09:23 UTC, arvidn approved these changes

2023-02-12 09:23 UTC, merged